# -*- coding: utf-8 -*-
"""tuples

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VFZthbZhywoJllKkvkBhGBznYtpEgQ0
"""

# Different types of tuples

my_tuple = ()
print(my_tuple)
my_tuple = (1,6,90,78,55,67,79,0)
print(my_tuple)
a, b, c = my_tuple
print(a)      
print(b)      
print(c)   
my_tuple = (1, "Hello", 3.4)
print(my_tuple)
my_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(my_tuple)
my_tuple = 3, 4.6, "dog"
print(my_tuple)

